@baseUrl= http://localhost:2000/api/v1


### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "maaz70724@gmail.com",
  "password": "SecurePassword12",
  "city": "New York",
  "country": "USA",
  "contactNo": "1234567890",
  "role": "Demo"
}

### Login User
POST http://localhost:2000/api/v1/auth/login
Content-Type: application/json

{
  "email": "compiletimeterro@gmail.com",
  "password": "SecurePassword12"
}



### 1️⃣ Forgot Password Request
POST http://localhost:8000/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "maaz70724@gmail.com"
}

### 2️⃣ Reset Password Request
POST http://localhost:8000/api/v1/auth/reset-password/066086bc83db244425054320cf6ecd72ba1f1e61624a652457df85d40008763d
Content-Type: application/json

{
  "newPassword": "maaz@123"
}

###
GET http://localhost:8000/api/v1/stock-data/ticker-data

###
GET https://stock-backend-ywib.onrender.com/api/v1/auth/real-users


###
GET http://166.62.87.152/~tauruson/data/

###
GET http://localhost:2000/api/v1/demo/stock-listing



###
POST {{baseUrl}}/demo-user/buy-stock
Content-Type: application/json

{
  "symbol": "PIBTL",
  "quantity": 10,
  "price": 10.18
}

